development:
  adapter: mysql
  encoding: utf8
  socket: /var/run/mysqld/mysqld.sock
  database: yology_devel
  username: yology_devel
  password: b7zqESTqnpXpeXLT
  pool: 5
  
test:
  # Sqlite Settings
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_test
  # username: root
  # password:
  # pool: 5
  
staging:
  adapter: mysql
  encoding: utf8
  database: yology_staging
  host: mysql.yology.org
  username: xxxxxx
  password: xxxxxx
  pool: 5
  
production:
  adapter: mysql
  encoding: utf8
  database: yology_production
  host: mysql.yology.org
  username: xxxxxx
  password: xxxxxx
  pool: 5
